Repository Arc-Computer/arc-memory, pull requests merged in 2025-05, with the labels that each got.

#18 feat(cli): Implement arc sim command structure and diff analysis
  arc_memory/attestation/__init__.py
  arc_memory/cli/__init__.py
  arc_memory/cli/sim.py
  arc_memory/simulate/__init__.py
  arc_memory/simulate/causal.py
  arc_memory/simulate/diff_utils.py
  tests/unit/simulate/__init__.py
  tests/unit/simulate/test_diff_utils.py
Labels: enhancement

#21 feat: implement simulation manifest generator
  arc_memory/cli/sim.py
  arc_memory/simulate/causal.py
  arc_memory/simulate/manifest.py
  tests/unit/simulate/test_causal.py
  tests/unit/simulate/test_manifest.py
Labels: enhancement

#23 feat: implement fault injection driver
  arc_memory/cli/sim.py
  arc_memory/simulate/code_interpreter.py
  arc_memory/simulate/fault_driver.py
  tests/unit/simulate/test_fault_driver.py
Labels: enhancement

#24 feat: implement LangGraph workflow
  arc_memory/cli/sim.py
  arc_memory/simulate/langgraph_flow.py
  docs/memory_integration.md
  tests/unit/simulate/test_langgraph_flow.py
Labels: enhancement

#25 Implement Results Analysis and Attestation
  .env.example
  .github/workflows/test-auth.yml
  .github/workflows/test-github-ingestion.yml
  arc_memory/attestation/__init__.py
  arc_memory/attestation/write_attest.py
  arc_memory/simulate/__init__.py
  arc_memory/simulate/explanation.py
  arc_memory/simulate/langgraph_flow.py
  pyproject.toml
  tests/conftest.py
  tests/integration/test_version.py
  tests/unit/attestation/test_write_attest.py
  tests/unit/simulate/test_code_interpreter.py
  tests/unit/simulate/test_explanation.py
  tests/unit/simulate/test_langgraph_flow.py
  tests/unit/test_github_rest_integration.py
Labels: enhancement

#26 Add comprehensive tests for Arc Sim implementation
  README.md
  arc_memory/simulate/mocks.py
  docs/cli/sim.md
  docs/examples/simulation.md
  tests/cli/test_sim.py
  tests/conftest.py
  tests/integration/test_sim_command.py
  tests/integration/test_sim_github_integration.py
  tests/unit/simulate/test_mocks.py
Labels: enhancement

#28 Linear Integration (API Key Auth)
  arc_memory/auth/linear.py
  arc_memory/cli/auth.py
  arc_memory/cli/build.py
  arc_memory/errors.py
  arc_memory/ingest/adr.py
  arc_memory/ingest/linear.py
  arc_memory/plugins.py
Labels: enhancement

#29 Linear OAuth 2.0 Integration
  .github/workflows/test-auth.yml
  arc_memory/auth/default_credentials.py
  arc_memory/auth/linear.py
  arc_memory/cli/auth.py
  arc_memory/ingest/linear.py
  docs/cli/auth.md
  docs/dev/linear-oauth.md
  docs/troubleshooting/linear-oauth.md
  tests/auth/test_linear_auth.py
  tests/auth/test_linear_oauth_flow.py
Labels: documentation, enhancement

#31 Update README.md with Linear OAuth authentication information
  README.md
Labels: documentation

#32 Set up GitHub App and Probot Framework for PR Bot
  arc-memory-pr-bot/.dockerignore
  arc-memory-pr-bot/.env.example
  arc-memory-pr-bot/.gitignore
  arc-memory-pr-bot/CODE_OF_CONDUCT.md
  arc-memory-pr-bot/CONTRIBUTING.md
  arc-memory-pr-bot/Dockerfile
  arc-memory-pr-bot/LICENSE
  arc-memory-pr-bot/README.md
  arc-memory-pr-bot/app.yml
  arc-memory-pr-bot/arc-pr-bot.yml.example
  arc-memory-pr-bot/package-lock.json
  arc-memory-pr-bot/package.json
  arc-memory-pr-bot/src/config.ts
  arc-memory-pr-bot/src/index.ts
  arc-memory-pr-bot/test/fixtures/issues.opened.json
  arc-memory-pr-bot/test/fixtures/mock-cert.pem
  arc-memory-pr-bot/test/fixtures/pull_request.opened.json
  arc-memory-pr-bot/test/index.test.ts
  arc-memory-pr-bot/tsconfig.json
  arc-memory-pr-bot/vitest.config.ts
  docs/pr-bot.md
Labels: enhancement

#33 Create Knowledge Graph Integration Layer for PR Bot
  arc-memory-pr-bot/package.json
  arc-memory-pr-bot/src/graph-service.ts
  arc-memory-pr-bot/src/index.ts
  arc-memory-pr-bot/src/mock-graph-data.ts
  arc-memory-pr-bot/src/mock-graph-service.ts
  arc-memory-pr-bot/test/graph-service.test.ts
  arc-memory-pr-bot/test/index.test.ts
Labels: enhancement

#35 LLM Integration for PR Bot
  arc-memory-pr-bot/package.json
  arc-memory-pr-bot/src/context-generator.ts
  arc-memory-pr-bot/src/index.ts
  arc-memory-pr-bot/src/llm/README.md
  arc-memory-pr-bot/src/llm/base-llm-client.ts
  arc-memory-pr-bot/src/llm/index.ts
  arc-memory-pr-bot/src/llm/llm-client-factory.ts
  arc-memory-pr-bot/src/llm/openai-client.ts
  arc-memory-pr-bot/src/llm/pr-context-processor.ts
  arc-memory-pr-bot/src/types/pg-protocol.d.ts
  arc-memory-pr-bot/test-llm-integration.js
  arc-memory-pr-bot/test-llm.sh
  arc-memory-pr-bot/tsconfig.json
Labels: enhancement

#38 Implement LLM Integration Phase 2 (Fixed)
  arc-memory-pr-bot/.env.analyze-example
  arc-memory-pr-bot/.env.example
  arc-memory-pr-bot/README.md
  arc-memory-pr-bot/TODO-PHASE2.md
  arc-memory-pr-bot/arc-pr-bot.yml.example
  arc-memory-pr-bot/package-lock.json
  arc-memory-pr-bot/run-bot.sh
  arc-memory-pr-bot/scripts/analyze-closed-prs.ts
  arc-memory-pr-bot/src/config.ts
  arc-memory-pr-bot/src/graph-service.ts
  arc-memory-pr-bot/src/index.ts
  arc-memory-pr-bot/src/llm/COMMENT-FORMATTER-PLAN.md
  arc-memory-pr-bot/src/llm/PR-BOT-INTEGRATION-PLAN.md
  arc-memory-pr-bot/src/llm/comment-formatter.ts
  arc-memory-pr-bot/src/llm/pr-context-processor.ts
  arc-memory-pr-bot/src/mock-graph-data.ts
  arc-memory-pr-bot/src/mock-graph-service.ts
  arc-memory-pr-bot/test/comment-formatter.test.ts
  arc-memory-pr-bot/test/index.test.ts
  arc-memory-pr-bot/tsconfig.json
Labels: enhancement

#48 Enhanced Knowledge Graph with Causal Relationships
  README.md
  arc_memory/cli/__init__.py
  arc_memory/cli/build.py
  arc_memory/cli/export.py
  arc_memory/export.py
  arc_memory/ingest/change_patterns.py
  arc_memory/ingest/code_analysis.py
  arc_memory/ingest/github.py
  arc_memory/ingest/github_fetcher.py
  arc_memory/llm/__init__.py
  arc_memory/llm/ollama_client.py
  arc_memory/plugins.py
  arc_memory/process/__init__.py
  arc_memory/process/causal_extraction.py
  arc_memory/process/kgot.py
  arc_memory/process/semantic_analysis.py
  arc_memory/process/temporal_analysis.py
  arc_memory/schema/models.py
  public/arc-research-architecture.png
  public/arc-vision-diagram.png
  public/arc-vision.png
  scripts/create_sample_causal_data.py
  tests/integration/test_enhanced_knowledge_graph.py
  tests/unit/test_causal_export.py
  tests/unit/test_causal_extraction.py
  tests/unit/test_causal_schema.py
  tests/unit/test_code_analysis.py
  tests/unit/test_enhanced_export.py
  tests/unit/test_export.py
  tests/unit/test_kgot.py
  tests/unit/test_kgot_enhanced.py
  tests/unit/test_llm_integration.py
  tests/unit/test_semantic_analysis.py
  tests/unit/test_temporal_analysis.py
Labels: enhancement

#49 Fix JavaScript/TypeScript LLM parsing errors
  arc_memory/ingest/code_analysis.py
  arc_memory/process/semantic_analysis.py
Labels: bug

#50 Arc search
  README.md
  arc_memory/cli/why.py
  arc_memory/llm/ollama_client.py
  arc_memory/semantic_search.py
  docs/cli/why.md
  tests/cli/test_why.py
  tests/unit/test_semantic_search.py
Labels: enhancement

#52 Implement Temporal Data Alignment in Schema
  arc_memory/cli/__init__.py
  arc_memory/cli/migrate.py
  arc_memory/ingest/github.py
  arc_memory/ingest/github_fetcher.py
  arc_memory/llm/ollama_client.py
  arc_memory/migrations/__init__.py
  arc_memory/migrations/add_timestamp_column.py
  arc_memory/process/temporal_analysis.py
  arc_memory/sql/db.py
  arc_memory/utils/__init__.py
  arc_memory/utils/temporal.py
  auto.md
  tests/legacy/unit/simulate/test_explanation.py
  tests/legacy/unit/simulate/test_fault_driver.py
  tests/legacy/unit/simulate/test_langgraph_flow.py
  tests/legacy/unit/simulate/test_manifest.py
  tests/legacy/unit/simulate/test_memory_integration.py
  tests/legacy/unit/simulate/test_mocks.py
  tests/utils/__init__.py
  tests/utils/test_temporal.py
Labels: enhancement

#53 Database Abstraction Layer and Metadata Utilities
  arc_memory/db/__init__.py
  arc_memory/db/base.py
  arc_memory/db/metadata.py
  arc_memory/db/neo4j_adapter.py
  arc_memory/db/sqlite_adapter.py
  tests/unit/test_db_adapters.py
  tests/unit/test_db_metadata.py
  tests/unit/test_neo4j_adapter.py
Labels: enhancement

#54 Fix abstraction in metadata utilities
  arc_memory/db/base.py
  arc_memory/db/metadata.py
  arc_memory/db/neo4j_adapter.py
  arc_memory/db/sqlite_adapter.py
  tests/unit/test_db_adapters.py
  tests/unit/test_db_metadata.py
  tests/unit/test_neo4j_adapter.py
Labels: enhancement

#55 Implement auto-refresh functionality
  .github/workflows/test-cli-commands.yml
  arc_memory/auto_refresh/__init__.py
  arc_memory/auto_refresh/core.py
  arc_memory/auto_refresh/sources/__init__.py
  arc_memory/auto_refresh/sources/adr.py
  arc_memory/auto_refresh/sources/github.py
  arc_memory/auto_refresh/sources/linear.py
  arc_memory/cli/__init__.py
  arc_memory/cli/refresh.py
  arc_memory/cli/relate.py
  arc_memory/cli/why.py
  arc_memory/config.py
  arc_memory/db/metadata.py
  arc_memory/errors.py
  arc_memory/process/temporal_analysis.py
  arc_memory/scheduler.py
  arc_memory/sql/db.py
  tests/cli/test_relate.py
  tests/cli/test_why.py
  tests/integration/test_auto_refresh.py
  tests/integration/test_enhanced_knowledge_graph.py
  tests/unit/test_auto_refresh.py
  tests/unit/test_temporal_analysis.py
Labels: enhancement

#56 SDK Core Implementation (PR #1)
  arc_memory/sdk/__init__.py
  arc_memory/sdk/adapters/__init__.py
  arc_memory/sdk/adapters/base.py
  arc_memory/sdk/adapters/registry.py
  arc_memory/sdk/core.py
  arc_memory/sdk/errors.py
  arc_memory/sdk/models.py
  tests/unit/test_sdk_core.py
Labels: enhancement

#57 PR 2a: Extract query functionality from CLI commands into the SDK
  arc_memory/cli/relate.py
  arc_memory/cli/why.py
  arc_memory/sdk/cache.py
  arc_memory/sdk/core.py
  arc_memory/sdk/decision_trail.py
  arc_memory/sdk/impact.py
  arc_memory/sdk/models.py
  arc_memory/sdk/progress.py
  arc_memory/sdk/query.py
  arc_memory/sdk/relationships.py
  arc_memory/sdk/temporal.py
  docs/roadmap/sdk_refactoring_plan.md
  tests/cli/test_relate.py
  tests/cli/test_why.py
  tests/sdk/__init__.py
  tests/sdk/test_cache.py
  tests/sdk/test_decision_trail.py
  tests/sdk/test_impact.py
  tests/sdk/test_progress.py
  tests/sdk/test_query.py
  tests/sdk/test_relationships.py
  tests/sdk/test_temporal.py
  tests/unit/test_relate_filtering.py
Labels: enhancement

#58 PR 2b: Extract export functionality from CLI commands into SDK
  arc_memory/cli/export.py
  arc_memory/sdk/core.py
  arc_memory/sdk/errors.py
  arc_memory/sdk/export.py
  arc_memory/sdk/models.py
  tests/integration/test_export_command.py
  tests/sdk/test_export.py
Labels: enhancement

#59 Update framework adapters for OpenAI and LangChain
  arc_memory/sdk/adapters/__init__.py
  arc_memory/sdk/adapters/langchain.py
  arc_memory/sdk/adapters/openai.py
  arc_memory/sdk/adapters/registry.py
  pyproject.toml
  tests/sdk/test_adapters.py
  tests/sdk/test_arc_adapters.py
Labels: enhancement

#60 PR #5: Add comprehensive SDK documentation and example agents
  arc_memory/__init__.py
  docs/README.md
  docs/cli/README.md
  docs/cli/sim.md
  docs/examples/README.md
  docs/examples/agents/code_review_agent.py
  docs/examples/agents/decision_tracker.py
  docs/examples/agents/impact_analyzer.py
  docs/examples/agents/langchain_integration.py
  docs/examples/agents/onboarding_agent.py
  docs/examples/agents/openai_integration.py
  docs/examples/sdk_examples.md
  docs/examples/simulation.md
  docs/getting_started.md
  docs/sdk/README.md
  docs/sdk/adapters.md
  docs/sdk/api_reference.md
Labels: documentation

#61 Remove unimplemented simulate module
  arc_memory/cli/__init__.py
  arc_memory/cli/sim.py
  arc_memory/simulate/__init__.py
  arc_memory/simulate/causal.py
  arc_memory/simulate/code_interpreter.py
  arc_memory/simulate/diff_utils.py
  arc_memory/simulate/explanation.py
  arc_memory/simulate/fault_driver.py
  arc_memory/simulate/langgraph_flow.py
  arc_memory/simulate/manifest.py
  arc_memory/simulate/mocks.py
  pyproject.toml
  tests/auth/test_auth_command.py
  tests/cli/test_sim.py
  tests/integration/__init__.py
  tests/integration/test_build_integration.py
  tests/integration/test_enhanced_knowledge_graph.py
  tests/integration/test_github_api_integration.py
  tests/integration/test_github_incremental_build.py
  tests/integration/test_sim_command.py
  tests/integration/test_sim_github_integration.py
  tests/integration/test_trace_comprehensive.py
  tests/legacy/unit/simulate/test_explanation.py
  tests/legacy/unit/simulate/test_fault_driver.py
  tests/legacy/unit/simulate/test_langgraph_flow.py
  tests/legacy/unit/simulate/test_manifest.py
  tests/legacy/unit/simulate/test_memory_integration.py
  tests/legacy/unit/simulate/test_mocks.py
  tests/unit/simulate/__init__.py
  tests/unit/simulate/test_causal.py
  tests/unit/simulate/test_code_interpreter.py
  tests/unit/simulate/test_diff_utils.py
  tests/unit/simulate/test_explanation.py
  tests/unit/simulate/test_fault_driver.py
  tests/unit/simulate/test_langgraph_flow.py
  tests/unit/simulate/test_manifest.py
  tests/unit/simulate/test_mocks.py
  tests/unit/test_enhanced_export.py
  tests/unit/test_llm_integration.py
  tests/unit/test_semantic_search.py
Labels: bug

#63 SDK QA Fixes: Documentation and Framework Adapter Improvements
  README.md
  arc_memory/sdk/adapters/langchain.py
  arc_memory/sdk/adapters/openai.py
  docs/examples/component_impact_analysis.md
  docs/examples/sdk_examples.md
  docs/getting_started.md
  docs/quickstart.md
  docs/sdk/README.md
  docs/sdk/adapters.md
  docs/sdk/api_reference.md
Labels: documentation

#64 Update version to 0.5.0 and improve Ollama integration
  arc_memory/__init__.py
  arc_memory/auth/github.py
  arc_memory/ingest/github.py
  arc_memory/ingest/github_graphql.py
  arc_memory/ingest/github_rest.py
  arc_memory/llm/ollama_client.py
  arc_memory/semantic_search.py
  pyproject.toml
  tests/qa/README.md
  tests/qa/qa_test_adapters.py
  tests/qa/qa_test_cli.py
  tests/qa/qa_test_documentation.py
  tests/qa/qa_test_functionality.py
  tests/qa/qa_test_installation.py
  tests/qa/qa_test_ollama.py
  tests/qa/qa_test_user_journey.py
Labels: documentation, enhancement

#66 Fix QA test issues for version 0.5.0
  arc_memory/db/sqlite_adapter.py
  arc_memory/sdk/core.py
  arc_memory/sdk/errors.py
  arc_memory/sdk/export.py
  tests/qa/qa_test_adapters.py
  tests/qa/qa_test_functionality.py
Labels: bug

#70 Add build method to Arc SDK and create example agents with GPT-4.1 as default
  .gitignore
  arc_memory/auto_refresh/core.py
  arc_memory/llm/openai_client.py
  arc_memory/sdk/core.py
  docs/examples/agents/code_review_agent.py
  docs/examples/agents/code_review_assistant.py
  docs/examples/agents/decision_tracker.py
  docs/examples/agents/impact_analyzer.py
  docs/examples/agents/incident_response_navigator.py
  docs/examples/agents/langchain_integration.py
  docs/examples/agents/onboarding_agent.py
  tests/unit/test_openai_enhancement.py
Labels: documentation, enhancement

#71 Optimize knowledge graph refresh for lower latency
  arc_memory/auto_refresh/core.py
  arc_memory/ingest/change_patterns.py
  arc_memory/migrations/add_metadata_column.py
  arc_memory/sql/db.py
  benchmarks/benchmark_results_incremental_20250514_143206.json
  benchmarks/benchmark_results_incremental_20250514_143953.json
  docs/examples/agents/code_review_assistant.py
  docs/examples/agents/incident_response_navigator.py
  tests/unit/test_incremental_build.py
Labels: documentation, enhancement

#72 Organize Demo Files and Implement Self-Healing Code Generation Loop
  arc_memory/ingest/change_patterns.py
  arc_memory/llm/openai_client.py
  demo/README.md
  demo/README_self_healing_loop.md
  demo/agents/blast_radius_viz.py
  demo/agents/code_generation_agent.py
  demo/agents/enhanced_blast_radius.py
  demo/agents/llm_powered_code_review.py
  demo/agents/pr_impact_analysis.py
  demo/agents/self_healing_loop.py
  demo/scripts/demo_blast_radius.sh
  demo/scripts/demo_code_review.sh
  demo/scripts/demo_enhanced_blast_radius.sh
  demo/scripts/demo_self_healing_loop.sh
  demo/scripts/run_self_healing_demo.py
  demo/self_healing_loop_technical.md
  demo/test_files/sample_code.py
  docs/examples/agents/README.md
  docs/examples/agents/code_review_assistant.py
  docs/examples/agents/llm_powered_blast_radius.py
Labels: documentation, enhancement

#73 Add repository identity and architecture schema features
  arc_memory/auto_refresh/core.py
  arc_memory/db/sqlite_adapter.py
  arc_memory/migrations/add_architecture_schema.py
  arc_memory/migrations/add_repo_id_column.py
  arc_memory/process/architecture_extraction.py
  arc_memory/schema/models.py
  arc_memory/sdk/core.py
  docs/api/models.md
  docs/sdk/api_reference.md
  pyproject.toml
  tests/integration/test_repository_architecture_integration.py
  tests/unit/schema/test_repository_architecture_models.py
  tests/unit/test_architecture_extraction.py
  tests/unit/test_architecture_queries.py
  tests/unit/test_llm_integration.py
  tests/unit/test_openai_enhancement.py
  tests/unit/test_repository_management.py
  tests/unit/test_sdk_core.py
  tests/unit/test_semantic_search.py
Labels: documentation, enhancement

#74 Add Code Time Machine demo with OpenAI reasoning model integration
  arc_memory/sdk/temporal.py
  demo/code_time_machine/README.md
  demo/code_time_machine/__init__.py
  demo/code_time_machine/code_time_machine.py
  demo/code_time_machine/custom_impact.py
  demo/code_time_machine/reasoning_engine.py
  demo/code_time_machine/run_demo.sh
  demo/code_time_machine/sample_queries.json
  demo/code_time_machine/visualizers/__init__.py
  demo/code_time_machine/visualizers/decision_visualizer.py
  demo/code_time_machine/visualizers/impact_visualizer.py
  demo/code_time_machine/visualizers/timeline_visualizer.py
Labels: documentation, enhancement

#75 Code Time Machine Demo Improvements
  README.md
  arc_memory/db/sqlite_adapter.py
  arc_memory/export.py
  arc_memory/process/kgot.py
  demo/code_time_machine/main.py
Labels: documentation

#77 Enhance Impact Analysis with Dynamic Scoring System
  arc_memory/sdk/impact.py
  tests/sdk/test_impact.py
Labels: enhancement

#76 Add baseline RL pipeline: environment, agent, reward, training, CLI, …
  arc_memory/cli/__init__.py
  arc_memory/cli/rl.py
  arc_memory/db/neo4j_adapter.py
  arc_memory/process/causal_extraction.py
  arc_memory/rl/README.md
  arc_memory/rl/__init__.py
  arc_memory/rl/agent.py
  arc_memory/rl/environment.py
  arc_memory/rl/reward.py
  arc_memory/rl/run.py
  arc_memory/rl/tests/__init__.py
  arc_memory/rl/tests/test_agent.py
  arc_memory/rl/tests/test_environment.py
  arc_memory/rl/tests/test_reward.py
  arc_memory/rl/training.py
  arc_memory/semantic_search.py
  docs/rl/PR_DESCRIPTION.md
  pyproject.toml
  tests/unit/test_semantic_search.py
Labels: enhancement

#78 Updated baseline RL pipeline with Q-learning for blast radius prediction
  .gitignore
  arc_memory/rl/agent.py
  arc_memory/rl/environment.py
  arc_memory/rl/run.py
  docs/rl/PR_DESCRIPTION.md
Labels: bug

#81 Starter Kit: Add Examples & GitHub Actions workflow demo
  demo/README.md
  demo/blast_radius_demo.py
  demo/code_relationships_demo.py
  demo/knowledge_query_demo.py
Labels: documentation

#82 Add multi-repository support
  CHANGELOG.md
  README.md
  arc_memory/__init__.py
  arc_memory/auto_refresh/core.py
  arc_memory/cli/__init__.py
  arc_memory/cli/build.py
  arc_memory/cli/repo.py
  arc_memory/db/sqlite_adapter.py
  arc_memory/llm/openai_client.py
  arc_memory/sdk/core.py
  arc_memory/sdk/query.py
  arc_memory/semantic_search.py
  demo/blast_radius_demo.py
  demo/code_relationships_demo.py
  demo/github-actions-readme.md
  demo/github-actions-workflow.yml
  demo/knowledge_query_demo.py
  docs/getting_started.md
  docs/multi_repository.md
  docs/quickstart.md
  pyproject.toml
  tests/cli/test_why.py
  tests/test_multi_repo.py
Labels: documentation, enhancement

#83 Fix LLM enhancement functions to accept llm_model parameter
  arc_memory/process/kgot.py
  arc_memory/process/semantic_analysis.py
  arc_memory/process/temporal_analysis.py
Labels: bug

#84 Enhanced Schema for Knowledge Graph
  CHANGELOG.md
  arc_memory/__init__.py
  arc_memory/cli/build.py
  arc_memory/db/sqlite_adapter.py
  arc_memory/llm/openai_client.py
  arc_memory/migrations/add_enhanced_schema.py
  arc_memory/process/semantic_analysis.py
  arc_memory/schema/models.py
  arc_memory/semantic_search.py
  demo/knowledge_query_demo.py
  pyproject.toml
  tests/test_enhanced_schema.py
  tests/unit/test_enhanced_schema.py
Labels: enhancement

#85 SDK Improvements: Health Check Methods, Standardized Confidence Scores, and Enhanced Error Messages
  CHANGELOG.md
  arc_memory/__init__.py
  arc_memory/sdk/core.py
  arc_memory/sdk/query.py
  pyproject.toml
Labels: enhancement

#86 Documentation Improvements
  README.md
  demo/simple_time_machine/README.md
  demo/simple_time_machine/__init__.py
  demo/simple_time_machine/main.py
  demo/simple_time_machine/utils.py
  demo/simple_time_machine/visualize_decisions.py
  demo/simple_time_machine/visualize_impact.py
  demo/simple_time_machine/visualize_timeline.py
  docs/architecture.md
  docs/examples/cross_repo_explorer/README.md
  docs/examples/cross_repo_explorer/analyzers/__init__.py
  docs/examples/cross_repo_explorer/analyzers/component_analyzer.py
  docs/examples/cross_repo_explorer/analyzers/decision_analyzer.py
  docs/examples/cross_repo_explorer/analyzers/dependency_analyzer.py
  docs/examples/cross_repo_explorer/cross_repo_explorer.py
  docs/examples/quickstart/README.md
  docs/examples/quickstart/__init__.py
  docs/examples/quickstart/quickstart.py
  docs/framework_integration.md
  docs/temporal_understanding.md
Labels: documentation

#90 Fix and update tests
  arc_memory/utils/temporal.py
  tests/sdk/test_query.py
  tests/unit/test_db_adapters.py
  tests/unit/test_github_fetcher.py
  tests/unit/test_kgot_enhanced.py
  tests/utils/test_temporal.py
Labels: bug

#91 Clarify agent write access in docs
  docs/README.md
  docs/examples/agents/README.md
  docs/sdk/README.md
Labels: documentation, codex

#87 Add Notion & Jira Integrations For Data Ingestion
  README.md
  arc_memory/auth/default_credentials.py
  arc_memory/auth/jira.py
  arc_memory/auth/notion.py
  arc_memory/cli/auth.py
  arc_memory/cli/build.py
  arc_memory/errors.py
  arc_memory/ingest/jira.py
  arc_memory/ingest/notion.py
  arc_memory/plugins.py
  arc_memory/tests/auth/test_jira_auth.py
  arc_memory/tests/auth/test_notion_auth.py
  docs/dev/notion-oauth.md
  docs/framework_integration.md
  docs/guides/jira_integration.md
Labels: documentation, enhancement

#92 Implemented the binary reward system
  .gitignore
  arc_memory/rl/README.md
  arc_memory/rl/benchmark.py
  arc_memory/rl/data_provider.py
  arc_memory/rl/environment.py
  arc_memory/rl/reward.py
  arc_memory/rl/run.py
Labels: bug, enhancement
